  name: Build QModem IPK

  on:
    push:
      branches: [ "main" ]
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Source
          uses: actions/checkout@v3

        - name: Set up build environment
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev python3 python3-pip unzip

        - name: Clone OpenWrt SDK
          run: |
            mkdir openwrt
            cd openwrt
            wget https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            tar -xf openwrt-sdk-*.tar.xz
            mv openwrt-sdk-* sdk
            cd sdk/package
            git clone https://github.com/FUjr/QModem qmodem

        - name: Create Makefile
          run: |
            cat <<EOF > openwrt/sdk/package/qmodem/Makefile
            include \$(TOPDIR)/rules.mk

            PKG_NAME:=qmodem
            PKG_VERSION:=1.0
            PKG_RELEASE:=1

            PKG_SOURCE_PROTO:=git
            PKG_SOURCE_URL:=https://github.com/FUjr/QModem.git
            PKG_SOURCE_VERSION:=HEAD

            PKG_LICENSE:=MIT
            include \$(INCLUDE_DIR)/package.mk

            define Package/qmodem
              SECTION:=utils
              CATEGORY:=Utilities
              TITLE:=QModem - SMS Tool
              DEPENDS:=+python3 +python3-pyserial
            endef

            define Build/Compile
              true
            endef

            define Package/qmodem/install
              \$(INSTALL_DIR) \$(1)/usr/bin
              \$(INSTALL_BIN) \$(PKG_BUILD_DIR)/qmodem.py \$(1)/usr/bin/qmodem
            endef

            \$(eval \$(call BuildPackage,qmodem))
            EOF

        - name: Build IPK
          run: |
            cd openwrt/sdk
            ./scripts/feeds update -a
            ./scripts/feeds install -a
            make defconfig
            make package/qmodem/compile V=s

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: qmodem-ipk
            path: openwrt/sdk/bin/packages/*/*/*.ipk
